name: Packages Build
on:
  push:
    branches:
      - develop

env:
  AZURE_WEBAPP_NAME: ords--main   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-everything:
    name: All Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: npm install, build
      run: |
        npm ci
        npm run build --workspaces --if-present
    - name: move main-application to host
      run: mv packages/main-application/build packages/main-host/build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: main-application
        retention-days: 7
        path: |
          packages/main-host
  deploy:
    name: Deploy & Build Host
    runs-on: ubuntu-latest
    needs: build-everything
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: main-application
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: npm install production dependencies
      run: |
        npm ci
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    