name: Packages Build
on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build-everything:
    name: All Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --workspaces --if-present
        npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: main-application
        retention-days: 5
        path: packages/main-application/build